#!/usr/bin/env bash
set -e

add() {
	[[ $2 ]] || { echo "Usage: steps add <step_name>" >&2; return 1; }
  local folder_path=`git rev-parse --show-prefix`
  git tag "steps_${folder_path}_$2"
}

remove() {
  [[ $2 ]] || { echo "Usage: steps remove <step_name>" >&2; return 1; }
  local folder_path=`git rev-parse --show-prefix`
  git tag -d "steps_${folder_path}_$2"
}

workon() {
	[[ $2 ]] || { echo "Usage: steps workon <step_name>" >&2; return 1; }
  local folder_path=`git rev-parse --show-prefix`
  git checkout "steps_${folder_path}_$2" > /dev/null
  local branch_name=steps_wip/${folder_path}_$2 

  git branch -d $branch_name || true # remove old WIP
  git checkout -b $branch_name 
}

view() {
	[[ $2 ]] || { echo "Usage: steps view <step_name>" >&2; return 1; }
  local folder_path=`git rev-parse --show-prefix`
  git checkout "steps_${folder_path}_$2" > /dev/null
}

update() {
    local current_branch=`git rev-parse --abbrev-ref HEAD`
    local current_tag=steps_`echo $current_branch | cut -c 11-` # cut of steps_wip/ part of branch

    git tag -d $current_tag
    git tag $current_tag

    git rebasetags $current_branch master
}

usage() {
  echo "Usage: steps <command>";
  echo "Commands: add, remove, workon, view, update";
}

if [ $# -eq 0 ]
  then
    usage
    exit 1
fi

case $1 in
    'add' )
        add "$@"
        exit 0
        ;;
    'remove' )
        remove "$@"
        exit 0
        ;;
    'workon' )
        workon "$@"
        exit 0
        ;;
    'view' )
        view "$@"
        exit 0
        ;;
    'update' )
        update "$@"
        exit 0
        ;;
    'help' )
        usage
        exit 0
        ;;
    *)
        echo "steps: unrecognized command '$1'" 1>&2
        usage
        exit 1
        ;;
esac
